apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: ingress-space
spec:
  selector:
    name: nginx-ingress
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    name: http
  - port: 443
    targetPort: 443
    name: https
