apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  containers:
    - name: nginx-pod
      image: nginx
      ports:
        - containerPort: 80
  nodeName: minikube-m02
