apiVersion: v1
kind: Pod
metadata:
  name: math
  labels:
    name: math
spec:
  restartPolicy: OnFailure
  containers:
    - name: math
      image: alpine
      command:
        - 'expr'
        - '3'
        - '+'
        - '2'
