apiVersion: v1
kind: Pod
metadata:
  name: bee
  labels:
    name: bee
spec:
  tolerations:
    - key: spray
      value: mortein
      effect: NoSchedule
  containers:
    - name: bee
      image: nginx
