apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    name: webapp
spec:
  containers:
    - name: webapp
      image: kodekloud/event-simulator
      volumeMounts:
        - name: logs
          mountPath: /log
  volumes:
    - name: logs
      persistentVolumeClaim:
        claimName: claim-log-1
