apiVersion: v1
kind: ReplicationController
metadata:
  name: appcake-rc
  labels:
    app: appcake
    tier: frontend

spec:
  replicas: 3
  template:
    metadata:
      name: appcake-pod
      labels:
        app: appcake
        tier: frontend

    spec:
      containers:
        - name: appcake-container
          image: nginx
